---
kind: pipeline
type: docker
name: Deploy OpenLDAP Server (dev)

clone:
  depth: 1

concurrency:
  limit: 1

steps:
  - name: configure & deploy
    image: docker.nexus.diesel.net/drone-ansible:2.13
    settings:
      playbook: .ansible/deploy.yaml
      inventory: .ansible/inventory/dev
      galaxy: .ansible/roles/requirements.yaml
      private_key:
        from_secret: automation_id_rsa
      vault_password:
        from_secret: ansible_vault_password

trigger:
  branch:
    - development
  event:
    - push

---
kind: pipeline
type: docker
name: Deploy OpenLDAP Server (prod)

clone:
  depth: 1

concurrency:
  limit: 1

steps:

  - name: configure & deploy
    image: docker.nexus.diesel.net/drone-ansible:2.13
    environment:
      LDAP_ADMIN_PASSWORD:
        from_secret: ldap_admin_password
    settings:
      playbook: .ansible/deploy.yaml
      inventory: .ansible/inventory/prod
      galaxy: .ansible/roles/requirements.yaml
      private_key:
        from_secret: automation_id_rsa
      vault_password:
        from_secret: ansible_vault_password


trigger:
  branch:
    - stable
  event:
    - push
...
