---
kind: pipeline
type: docker
name: Install OpenLDAP Server

clone:
  depth: 1

steps:
  - name: deploy
    image: plugins/ansible:3
    environment:
      ANSIBLE_CONFIG: .ansible/ansible.cfg
    settings:
      playbook: .ansible/deploy.yaml
      galaxy: .ansible/roles/requirements.yaml
      private_key:
        from_secret: ansible_private_key
      vault_password:
        from_secret: ansible_vault_password
    commands:
      # dynamically select inventory based on Git branch/tag
      - version=$DRONE_BRANCH
      - if [ ! -z $DRONE_TAG ]; then version=production; fi
      - /bin/drone-ansible --inventory .ansible/inventory/$$version/hosts

trigger:
  branch:
    - development
    - stable
  event:
    - push
...
